server:
  port: 9095
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pradyumna1979/CONFIG-SERVER
          search-paths: user-service,payment-service,notification-service,shipment-service
          clone-on-start: true
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

